/* =====================================================
   PhilipG — Question Bank
   Common Core-aligned for grades 1 and 4.
   subject: math | reading | spelling | grammar
   Edit freely — game picks random questions per battle.
   ===================================================== */

const QUESTIONS = {
  // ================================================
  // GRADE 1 — Philip (just finished 1st grade)
  // ================================================
  grade1: {
    math: [
      { text: "What is 2 + 3?", choices: ["4", "5", "6", "7"], answer: 1 },
      { text: "What is 7 - 4?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "What is 5 + 5?", choices: ["9", "10", "11", "12"], answer: 1 },
      { text: "What is 9 - 3?", choices: ["5", "6", "7", "8"], answer: 1 },
      { text: "What is 6 + 4?", choices: ["8", "9", "10", "11"], answer: 2 },
      { text: "What is 8 + 2?", choices: ["10", "9", "11", "12"], answer: 0 },
      { text: "What is 10 - 5?", choices: ["3", "4", "5", "6"], answer: 2 },
      { text: "What is 4 + 6?", choices: ["8", "9", "10", "11"], answer: 2 },
      { text: "What is 12 - 4?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "What is 7 + 7?", choices: ["12", "13", "14", "15"], answer: 2 },
      { text: "What is 11 - 6?", choices: ["3", "4", "5", "6"], answer: 2 },
      { text: "What is 3 + 8?", choices: ["10", "11", "12", "13"], answer: 1 },
      { text: "What is 15 - 7?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "Count by 2s: 2, 4, 6, ?", choices: ["7", "8", "9", "10"], answer: 1 },
      { text: "Count by 5s: 5, 10, 15, ?", choices: ["17", "18", "19", "20"], answer: 3 },
      { text: "Count by 10s: 10, 20, 30, ?", choices: ["35", "40", "45", "50"], answer: 1 },
      { text: "Which number is greater: 17 or 12?", choices: ["12", "17", "they're equal", "neither"], answer: 1 },
      { text: "Which number is smaller: 8 or 14?", choices: ["8", "14", "they're equal", "neither"], answer: 0 },
      { text: "How many sides does a triangle have?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "How many sides does a square have?", choices: ["3", "4", "5", "6"], answer: 1 },
      { text: "What shape has no sides?", choices: ["square", "triangle", "circle", "rectangle"], answer: 2 },
      { text: "If it is 3 o'clock, what time will it be in 1 hour?", choices: ["2 o'clock", "3:30", "4 o'clock", "5 o'clock"], answer: 2 },
      { text: "Sam has 6 apples. He eats 2. How many are left?", choices: ["2", "3", "4", "5"], answer: 2 },
      { text: "Lisa has 4 cats and gets 3 more. How many cats now?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "What number comes after 19?", choices: ["18", "20", "21", "29"], answer: 1 },
      { text: "What number comes before 13?", choices: ["11", "12", "14", "15"], answer: 1 },
      { text: "What is 10 + 10?", choices: ["10", "15", "20", "25"], answer: 2 },
      { text: "What is half of 10?", choices: ["2", "4", "5", "6"], answer: 2 },
      { text: "Which is heaviest: a feather, a brick, or paper?", choices: ["feather", "brick", "paper", "they're equal"], answer: 1 },
      { text: "What is 1 + 1 + 1?", choices: ["2", "3", "4", "5"], answer: 1 },
    ],
    reading: [
      { text: "Which word rhymes with 'cat'?", choices: ["dog", "hat", "fish", "tree"], answer: 1 },
      { text: "Which word rhymes with 'sun'?", choices: ["moon", "fun", "star", "sky"], answer: 1 },
      { text: "Which word rhymes with 'book'?", choices: ["read", "page", "look", "word"], answer: 2 },
      { text: "Which word starts with the same sound as 'ball'?", choices: ["apple", "bear", "cat", "dog"], answer: 1 },
      { text: "Which word starts with the same sound as 'snake'?", choices: ["sun", "tree", "moon", "frog"], answer: 0 },
      { text: "What is the opposite of 'big'?", choices: ["large", "small", "huge", "tall"], answer: 1 },
      { text: "What is the opposite of 'hot'?", choices: ["warm", "cool", "cold", "wet"], answer: 2 },
      { text: "What is the opposite of 'up'?", choices: ["high", "low", "down", "side"], answer: 2 },
      { text: "What is the opposite of 'happy'?", choices: ["mad", "sad", "tired", "sleepy"], answer: 1 },
      { text: "Which is a color?", choices: ["five", "blue", "run", "jump"], answer: 1 },
      { text: "Which is an animal?", choices: ["chair", "rock", "rabbit", "tree"], answer: 2 },
      { text: "Which is a number?", choices: ["seven", "purple", "shoe", "cup"], answer: 0 },
      { text: "If Tom ran fast, how did Tom run?", choices: ["slow", "fast", "loud", "soft"], answer: 1 },
      { text: "The dog is wet. What happened to the dog?", choices: ["it slept", "it got water on it", "it ate", "it ran"], answer: 1 },
      { text: "Pick the word that means very small.", choices: ["huge", "tiny", "long", "wide"], answer: 1 },
      { text: "Pick the word that means very fast.", choices: ["slow", "quick", "sleepy", "still"], answer: 1 },
      { text: "Which word is a sight word?", choices: ["the", "blarg", "zoozle", "quibz"], answer: 0 },
      { text: "Which word means 'a place to sleep'?", choices: ["bed", "chair", "table", "sink"], answer: 0 },
      { text: "If I am cold, what should I wear?", choices: ["shorts", "tank top", "coat", "swimsuit"], answer: 2 },
      { text: "What do you do with a book?", choices: ["eat it", "read it", "kick it", "wear it"], answer: 1 },
      { text: "What is the first letter of 'apple'?", choices: ["a", "b", "c", "p"], answer: 0 },
      { text: "What is the last letter of 'cat'?", choices: ["c", "a", "t", "s"], answer: 2 },
      { text: "How many letters in the word 'sun'?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "Which word rhymes with 'tree'?", choices: ["leaf", "bee", "root", "branch"], answer: 1 },
      { text: "What sound does a 'sh' make?", choices: ["ssss", "shhh", "ffff", "tttt"], answer: 1 },
    ],
    spelling: [
      { text: "Spell the word for the picture below: 🐕", choices: ["dog", "dgo", "dag", "doog"], answer: 0 },
      { text: "Spell the word: 🐱", choices: ["kat", "cat", "katt", "cot"], answer: 1 },
      { text: "Spell the word: ☀️", choices: ["sun", "son", "sin", "soun"], answer: 0 },
      { text: "Spell the word: 🌙", choices: ["moun", "mun", "moon", "mone"], answer: 2 },
      { text: "Spell the word: 🚗", choices: ["kar", "carr", "car", "cor"], answer: 2 },
      { text: "Spell the word: 🏠", choices: ["hous", "house", "hawse", "hous"], answer: 1 },
      { text: "Spell the word: 🐟", choices: ["fish", "fis", "phish", "fich"], answer: 0 },
      { text: "Spell the word: 🐦", choices: ["brid", "burd", "bird", "berd"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["frend", "freind", "friend", "freand"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["becuz", "becauz", "because", "becose"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["wuz", "was", "waz", "wos"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["sed", "saed", "said", "sayd"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["plae", "play", "pley", "plae"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["red", "reed", "rede", "ree"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["jump", "jumpe", "jamp", "jumpp"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["lik", "like", "liek", "likke"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["bik", "bike", "biek", "bikke"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["mak", "make", "maek", "mayk"], answer: 1 },
      { text: "Fill in the blank: c_t (a cat)", choices: ["a", "e", "i", "o"], answer: 0 },
      { text: "Fill in the blank: d_g (a dog)", choices: ["a", "e", "i", "o"], answer: 3 },
      { text: "Fill in the blank: b_g (a bug)", choices: ["a", "e", "i", "u"], answer: 3 },
      { text: "Which word has a silent 'e'?", choices: ["cat", "cake", "dog", "sun"], answer: 1 },
      { text: "Spell the word that means the color of snow.", choices: ["wite", "whight", "white", "whit"], answer: 2 },
      { text: "Spell the word: a body part you walk on.", choices: ["foot", "fot", "fute", "fuut"], answer: 0 },
      { text: "Spell the word: where birds live.", choices: ["nest", "nast", "neast", "nezt"], answer: 0 },
    ],
    grammar: [
      { text: "A noun is a...", choices: ["person, place, or thing", "action word", "color", "feeling"], answer: 0 },
      { text: "A verb is a...", choices: ["thing", "action word", "name", "color"], answer: 1 },
      { text: "Which word is a noun?", choices: ["run", "happy", "dog", "quickly"], answer: 2 },
      { text: "Which word is a verb?", choices: ["car", "jump", "blue", "sleepy"], answer: 1 },
      { text: "Which word is a noun?", choices: ["sing", "tree", "fast", "loud"], answer: 1 },
      { text: "Which word is a verb?", choices: ["happy", "house", "run", "red"], answer: 2 },
      { text: "Sentences begin with what kind of letter?", choices: ["capital", "lowercase", "any letter", "a number"], answer: 0 },
      { text: "Sentences end with...", choices: ["a letter", "a punctuation mark", "a number", "nothing"], answer: 1 },
      { text: "Which is a complete sentence?", choices: ["The cat.", "Ran fast.", "The cat ran fast.", "Fast cat."], answer: 2 },
      { text: "Which is a complete sentence?", choices: ["My dog", "Barks loud.", "My dog barks.", "Dog loud"], answer: 2 },
      { text: "What is the plural of 'cat'?", choices: ["cat", "cats", "cates", "caties"], answer: 1 },
      { text: "What is the plural of 'box'?", choices: ["boxs", "boxes", "boxies", "box"], answer: 1 },
      { text: "What is the plural of 'baby'?", choices: ["babys", "babes", "babies", "babys"], answer: 2 },
      { text: "Which word means more than one mouse?", choices: ["mouses", "mice", "mooses", "mousies"], answer: 1 },
      { text: "Should we say 'I ___ happy'?", choices: ["am", "is", "are", "be"], answer: 0 },
      { text: "Should we say 'She ___ running'?", choices: ["am", "is", "are", "be"], answer: 1 },
      { text: "Should we say 'They ___ playing'?", choices: ["am", "is", "are", "be"], answer: 2 },
      { text: "Which sentence is correct?", choices: ["the dog runs.", "The dog runs.", "the Dog Runs", "THE DOG RUNS"], answer: 1 },
      { text: "Which sentence asks a question?", choices: ["I am tall.", "Are you tall?", "I am tall!", "Tall am I."], answer: 1 },
      { text: "Which word names a place?", choices: ["jump", "park", "happy", "loud"], answer: 1 },
      { text: "Capitalize names. Which is right?", choices: ["my friend sam", "My friend Sam", "my Friend sam", "MY friend sam"], answer: 1 },
      { text: "Pick the action word in: 'The bird flies.'", choices: ["The", "bird", "flies", "the"], answer: 2 },
      { text: "Pick the action word in: 'I eat apples.'", choices: ["I", "eat", "apples", "the"], answer: 1 },
      { text: "What punctuation mark ends an exciting sentence?", choices: [".", "?", "!", ","], answer: 2 },
      { text: "What punctuation mark ends a question?", choices: [".", "?", "!", ","], answer: 1 },
    ],
  },

  // ================================================
  // GRADE 4 — Owen (just finished 4th grade)
  // ================================================
  grade4: {
    math: [
      { text: "What is 24 × 6?", choices: ["124", "134", "144", "154"], answer: 2 },
      { text: "What is 15 × 12?", choices: ["170", "180", "190", "200"], answer: 1 },
      { text: "What is 144 ÷ 12?", choices: ["10", "11", "12", "13"], answer: 2 },
      { text: "What is 96 ÷ 8?", choices: ["10", "11", "12", "13"], answer: 2 },
      { text: "What is 357 + 248?", choices: ["595", "605", "615", "705"], answer: 1 },
      { text: "What is 902 - 387?", choices: ["505", "515", "525", "615"], answer: 1 },
      { text: "What is 7 × 8?", choices: ["54", "56", "58", "64"], answer: 1 },
      { text: "What is 63 ÷ 9?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "What is 1/2 + 1/4?", choices: ["1/6", "2/6", "3/4", "1/4"], answer: 2 },
      { text: "What is 3/4 - 1/4?", choices: ["1/4", "1/2", "3/4", "1/8"], answer: 1 },
      { text: "Which fraction is equal to 1/2?", choices: ["2/3", "3/6", "2/5", "4/5"], answer: 1 },
      { text: "Which is greater: 0.5 or 0.45?", choices: ["0.5", "0.45", "they're equal", "neither"], answer: 0 },
      { text: "Round 487 to the nearest 100.", choices: ["400", "480", "490", "500"], answer: 3 },
      { text: "Round 6,342 to the nearest 1,000.", choices: ["5,000", "6,000", "6,500", "7,000"], answer: 1 },
      { text: "What is the area of a rectangle 8 cm long and 5 cm wide?", choices: ["13 cm²", "26 cm²", "40 cm²", "45 cm²"], answer: 2 },
      { text: "What is the perimeter of a square with side 7?", choices: ["14", "21", "28", "49"], answer: 2 },
      { text: "How many minutes in 2 hours?", choices: ["60", "100", "120", "150"], answer: 2 },
      { text: "How many seconds in 3 minutes?", choices: ["120", "150", "180", "210"], answer: 2 },
      { text: "If a movie starts at 4:15 and ends at 6:00, how long is it?", choices: ["1 hr 30 min", "1 hr 45 min", "2 hr", "2 hr 15 min"], answer: 1 },
      { text: "A pizza has 8 slices. If you eat 3, what fraction is left?", choices: ["3/8", "5/8", "3/5", "8/3"], answer: 1 },
      { text: "What is 25% of 100?", choices: ["20", "25", "50", "75"], answer: 1 },
      { text: "What is 50% of 80?", choices: ["20", "30", "40", "50"], answer: 2 },
      { text: "Which is a prime number?", choices: ["4", "6", "9", "11"], answer: 3 },
      { text: "Which is NOT a prime number?", choices: ["3", "5", "9", "7"], answer: 2 },
      { text: "What is 9 × 9?", choices: ["72", "79", "81", "91"], answer: 2 },
      { text: "What is 12 × 11?", choices: ["121", "122", "132", "144"], answer: 2 },
      { text: "A box has 6 rows of 9 candies. How many candies total?", choices: ["45", "54", "63", "69"], answer: 1 },
      { text: "If 4 friends share 32 cookies equally, how many each?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "Convert 3 feet to inches.", choices: ["12", "24", "36", "48"], answer: 2 },
      { text: "How many ounces in a pound?", choices: ["8", "12", "16", "32"], answer: 2 },
      { text: "What is the next number in the pattern: 3, 6, 12, 24, ?", choices: ["36", "42", "48", "72"], answer: 2 },
      { text: "Which angle is greater than 90°?", choices: ["acute", "right", "obtuse", "straight"], answer: 2 },
    ],
    reading: [
      { text: "What does 'enormous' mean?", choices: ["tiny", "very big", "fast", "smelly"], answer: 1 },
      { text: "What does 'ancient' mean?", choices: ["new", "very old", "fast", "loud"], answer: 1 },
      { text: "What does 'cautious' mean?", choices: ["careful", "careless", "loud", "happy"], answer: 0 },
      { text: "What does 'frequent' mean?", choices: ["rare", "happening often", "lost", "broken"], answer: 1 },
      { text: "What is the synonym of 'happy'?", choices: ["sad", "joyful", "tired", "angry"], answer: 1 },
      { text: "What is the antonym of 'difficult'?", choices: ["hard", "tricky", "easy", "tough"], answer: 2 },
      { text: "Which is the main idea of a paragraph?", choices: ["the title", "a detail", "what it is mostly about", "the last word"], answer: 2 },
      { text: "When you 'infer' from a text, you...", choices: ["copy it", "use clues to figure it out", "ignore it", "read it loudly"], answer: 1 },
      { text: "If the story says 'her eyes filled with tears,' she probably feels...", choices: ["excited", "sad", "hungry", "fast"], answer: 1 },
      { text: "A 'character' in a story is a...", choices: ["person or animal in it", "type of paper", "color", "place"], answer: 0 },
      { text: "The 'setting' of a story is the...", choices: ["main person", "where and when it happens", "ending", "first word"], answer: 1 },
      { text: "The 'plot' of a story is the...", choices: ["place", "events that happen", "title", "author"], answer: 1 },
      { text: "Which word means 'to make smaller'?", choices: ["enlarge", "shrink", "stretch", "build"], answer: 1 },
      { text: "Which word means 'to praise'?", choices: ["scold", "compliment", "ignore", "hide"], answer: 1 },
      { text: "Context clue: 'The dog was famished, so he gobbled his food.' What does famished mean?", choices: ["sleepy", "full", "very hungry", "scared"], answer: 2 },
      { text: "Context clue: 'The fragile vase shattered when it fell.' What does fragile mean?", choices: ["strong", "easily broken", "old", "tall"], answer: 1 },
      { text: "What does the prefix 're-' usually mean?", choices: ["not", "again", "before", "after"], answer: 1 },
      { text: "What does the prefix 'un-' usually mean?", choices: ["again", "not", "with", "before"], answer: 1 },
      { text: "What does the suffix '-less' mean?", choices: ["full of", "without", "before", "after"], answer: 1 },
      { text: "What does 'unhappy' mean?", choices: ["very happy", "not happy", "happy again", "always happy"], answer: 1 },
      { text: "What does 'rewrite' mean?", choices: ["write before", "not write", "write again", "right side"], answer: 2 },
      { text: "Which is a fact (not opinion)?", choices: ["Pizza tastes the best", "Water freezes at 32°F", "Blue is prettiest", "Math is fun"], answer: 1 },
      { text: "Which is an opinion (not fact)?", choices: ["A week has 7 days", "Earth has 1 moon", "Chocolate is the best flavor", "Birds lay eggs"], answer: 2 },
      { text: "An author's purpose can be to...", choices: ["only entertain", "inform, persuade, or entertain", "only inform", "only persuade"], answer: 1 },
      { text: "A 'simile' compares two things using...", choices: ["only nouns", "'like' or 'as'", "numbers", "questions"], answer: 1 },
      { text: "'Her smile was as bright as the sun' is an example of a...", choices: ["fact", "metaphor", "simile", "rhyme"], answer: 2 },
    ],
    spelling: [
      { text: "Which is spelled correctly?", choices: ["beleive", "believe", "belive", "beleeve"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["recieve", "receive", "receeve", "receive"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["seperate", "seperete", "separate", "separete"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["definately", "definitely", "definitley", "definatly"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["necessary", "neccessary", "nesessary", "neccesary"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["embarass", "embarrass", "embarras", "embaras"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["beautifull", "beutiful", "beautiful", "beautyful"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["different", "diffrent", "diferent", "diffirent"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["because", "becuase", "becouse", "becase"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["friend", "freind", "frend", "friand"], answer: 0 },
      { text: "Homophone: ___ are going to the park. (their/there/they're)", choices: ["their", "there", "they're", "thier"], answer: 2 },
      { text: "Homophone: I left my book over ___ . (their/there/they're)", choices: ["their", "there", "they're", "thier"], answer: 1 },
      { text: "Homophone: ___ shoes are muddy. (their/there/they're)", choices: ["their", "there", "they're", "thier"], answer: 0 },
      { text: "Homophone: I want ___ go home. (to/two/too)", choices: ["to", "two", "too", "twoo"], answer: 0 },
      { text: "Homophone: He has ___ apples. (to/two/too)", choices: ["to", "two", "too", "twoo"], answer: 1 },
      { text: "Homophone: It is ___ cold. (to/two/too)", choices: ["to", "two", "too", "twoo"], answer: 2 },
      { text: "Homophone: ___ raining outside. (its/it's)", choices: ["its", "it's", "its'", "itss"], answer: 1 },
      { text: "Homophone: The dog wagged ___ tail. (its/it's)", choices: ["its", "it's", "its'", "itss"], answer: 0 },
      { text: "Which is the plural of 'leaf'?", choices: ["leafs", "leaves", "leafes", "leavies"], answer: 1 },
      { text: "Which is the plural of 'child'?", choices: ["childs", "childes", "children", "childies"], answer: 2 },
      { text: "Which is the plural of 'foot'?", choices: ["foots", "feets", "feet", "footes"], answer: 2 },
      { text: "Add the suffix -ed: 'hop' becomes...", choices: ["hoped", "hopd", "hopped", "hoping"], answer: 2 },
      { text: "Add the suffix -ing: 'run' becomes...", choices: ["runing", "runned", "running", "ranning"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["truely", "truly", "trully", "truley"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["happend", "happenned", "happened", "hapened"], answer: 2 },
    ],
    grammar: [
      { text: "Which is a proper noun?", choices: ["city", "Houston", "park", "river"], answer: 1 },
      { text: "Which is a common noun?", choices: ["Sarah", "Texas", "school", "Monday"], answer: 2 },
      { text: "Which is an adjective?", choices: ["jump", "happy", "carefully", "and"], answer: 1 },
      { text: "Which is an adverb?", choices: ["fast", "quickly", "house", "blue"], answer: 1 },
      { text: "Which is a pronoun?", choices: ["dog", "she", "running", "tall"], answer: 1 },
      { text: "Which is a conjunction?", choices: ["and", "happy", "red", "jumps"], answer: 0 },
      { text: "In 'The big red dog,' what are 'big' and 'red'?", choices: ["nouns", "verbs", "adjectives", "adverbs"], answer: 2 },
      { text: "In 'She runs quickly,' what is 'quickly'?", choices: ["noun", "verb", "adjective", "adverb"], answer: 3 },
      { text: "Identify the subject in: 'The cat slept on the rug.'", choices: ["the cat", "slept", "rug", "on"], answer: 0 },
      { text: "Identify the predicate in: 'My brother plays soccer.'", choices: ["My brother", "plays soccer", "soccer", "my"], answer: 1 },
      { text: "Which is past tense of 'go'?", choices: ["goed", "gone", "went", "going"], answer: 2 },
      { text: "Which is past tense of 'eat'?", choices: ["eated", "ate", "eaten", "eating"], answer: 1 },
      { text: "Which is past tense of 'see'?", choices: ["seen", "saw", "seed", "seeing"], answer: 1 },
      { text: "Which is past tense of 'run'?", choices: ["runned", "running", "ran", "run"], answer: 2 },
      { text: "Which sentence is correct?", choices: ["She don't like fish.", "She doesn't like fish.", "She not like fish.", "She no like fish."], answer: 1 },
      { text: "Which sentence is correct?", choices: ["Me and Sam went.", "Sam and I went.", "I and Sam went.", "Sam and me went."], answer: 1 },
      { text: "Where does the comma go? 'I bought milk eggs and bread.'", choices: ["milk eggs and bread", "milk, eggs, and bread", "milk eggs, and bread", "milk eggs and, bread"], answer: 1 },
      { text: "Which uses quotation marks correctly?", choices: ["She said hello.", "She said, \"hello\".", "She said, \"Hello.\"", "She said: hello"], answer: 2 },
      { text: "Apostrophes show...", choices: ["only questions", "possession or contractions", "only the ending", "only past tense"], answer: 1 },
      { text: "Which is correct? 'The ___ tail wagged.'", choices: ["dogs", "dog's", "dogs'", "dogses"], answer: 1 },
      { text: "Which is correct? 'The ___ tails wagged.' (more than one dog)", choices: ["dog's", "dogs", "dogs'", "dogses"], answer: 2 },
      { text: "Contraction for 'do not'?", choices: ["donot", "don't", "do'nt", "dont"], answer: 1 },
      { text: "Contraction for 'I am'?", choices: ["Im", "I'm", "Iam", "I'am"], answer: 1 },
      { text: "Contraction for 'they are'?", choices: ["thery", "there", "they're", "theyre"], answer: 2 },
      { text: "Which type of sentence is 'Watch out!'?", choices: ["statement", "question", "exclamation", "command"], answer: 2 },
      { text: "Which type of sentence is 'Close the door.'?", choices: ["statement", "question", "exclamation", "command"], answer: 3 },
    ],
  },
};

// Helper: get a random question from a grade + subject
function getRandomQuestion(grade, subject) {
  const pool = QUESTIONS[grade] && QUESTIONS[grade][subject];
  if (!pool || pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

// Helper: shuffle answer choices but track correct index
function shuffleQuestion(q) {
  const indexed = q.choices.map((c, i) => ({ c, correct: i === q.answer }));
  for (let i = indexed.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [indexed[i], indexed[j]] = [indexed[j], indexed[i]];
  }
  return {
    text: q.text,
    choices: indexed.map(x => x.c),
    answer: indexed.findIndex(x => x.correct),
  };
}
