/* =====================================================
   PhilipG — Question Bank
   Common Core-aligned for grades 1 and 4.
   subject: math | reading | spelling | grammar
   Edit freely — game picks random questions per battle.

   Counts: ~90 per subject per grade = ~720 total
   ===================================================== */

const QUESTIONS = {
  // ================================================
  // GRADE 1 — Philip (just finished 1st grade)
  // ================================================
  grade1: {
    math: [
      // Basic addition
      { text: "What is 2 + 3?", choices: ["4", "5", "6", "7"], answer: 1 },
      { text: "What is 5 + 5?", choices: ["9", "10", "11", "12"], answer: 1 },
      { text: "What is 6 + 4?", choices: ["8", "9", "10", "11"], answer: 2 },
      { text: "What is 8 + 2?", choices: ["10", "9", "11", "12"], answer: 0 },
      { text: "What is 4 + 6?", choices: ["8", "9", "10", "11"], answer: 2 },
      { text: "What is 7 + 7?", choices: ["12", "13", "14", "15"], answer: 2 },
      { text: "What is 3 + 8?", choices: ["10", "11", "12", "13"], answer: 1 },
      { text: "What is 11 + 2?", choices: ["12", "13", "14", "15"], answer: 1 },
      { text: "What is 6 + 6?", choices: ["10", "11", "12", "13"], answer: 2 },
      { text: "What is 9 + 9?", choices: ["16", "17", "18", "19"], answer: 2 },
      { text: "What is 13 + 5?", choices: ["17", "18", "19", "20"], answer: 1 },
      { text: "What is 7 + 9?", choices: ["14", "15", "16", "17"], answer: 2 },
      { text: "What is 8 + 6?", choices: ["12", "13", "14", "15"], answer: 2 },
      { text: "What is 0 + 8?", choices: ["0", "7", "8", "9"], answer: 2 },
      { text: "What is 5 + 8?", choices: ["12", "13", "14", "15"], answer: 1 },
      { text: "What is 4 + 9?", choices: ["12", "13", "14", "15"], answer: 1 },
      { text: "What is 10 + 10?", choices: ["10", "15", "20", "25"], answer: 2 },
      { text: "What is 1 + 1 + 1?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "What is 2 + 2 + 2?", choices: ["4", "6", "8", "10"], answer: 1 },
      { text: "What is 5 + 5 + 5?", choices: ["10", "12", "15", "20"], answer: 2 },
      // Basic subtraction
      { text: "What is 7 - 4?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "What is 9 - 3?", choices: ["5", "6", "7", "8"], answer: 1 },
      { text: "What is 10 - 5?", choices: ["3", "4", "5", "6"], answer: 2 },
      { text: "What is 12 - 4?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "What is 11 - 6?", choices: ["3", "4", "5", "6"], answer: 2 },
      { text: "What is 15 - 7?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "What is 14 - 7?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "What is 18 - 9?", choices: ["7", "8", "9", "10"], answer: 2 },
      { text: "What is 20 - 10?", choices: ["8", "9", "10", "11"], answer: 2 },
      { text: "What is 16 - 8?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "What is 17 - 9?", choices: ["7", "8", "9", "10"], answer: 1 },
      { text: "What is 11 - 4?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "What is 13 - 6?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "What is 8 - 0?", choices: ["0", "7", "8", "9"], answer: 2 },
      { text: "What is 20 - 5?", choices: ["13", "14", "15", "16"], answer: 2 },
      { text: "What is 12 - 6?", choices: ["5", "6", "7", "8"], answer: 1 },
      { text: "What is 19 - 4?", choices: ["13", "14", "15", "16"], answer: 2 },
      { text: "What is 10 - 1 - 1?", choices: ["7", "8", "9", "10"], answer: 1 },
      // Skip counting
      { text: "Count by 2s: 2, 4, 6, ?", choices: ["7", "8", "9", "10"], answer: 1 },
      { text: "Count by 2s: 8, 10, 12, ?", choices: ["13", "14", "15", "16"], answer: 1 },
      { text: "Count by 2s: 14, 16, 18, ?", choices: ["19", "20", "21", "22"], answer: 1 },
      { text: "Count by 5s: 5, 10, 15, ?", choices: ["17", "18", "19", "20"], answer: 3 },
      { text: "Count by 5s: 20, 25, 30, ?", choices: ["33", "34", "35", "40"], answer: 2 },
      { text: "Count by 5s: 35, 40, 45, ?", choices: ["46", "48", "50", "55"], answer: 2 },
      { text: "Count by 10s: 10, 20, 30, ?", choices: ["35", "40", "45", "50"], answer: 1 },
      { text: "Count by 10s: 50, 60, 70, ?", choices: ["75", "80", "85", "90"], answer: 1 },
      { text: "Count by 10s: 70, 80, 90, ?", choices: ["95", "100", "101", "110"], answer: 1 },
      // Compare numbers
      { text: "Which number is greater: 17 or 12?", choices: ["12", "17", "equal", "neither"], answer: 1 },
      { text: "Which number is smaller: 8 or 14?", choices: ["8", "14", "equal", "neither"], answer: 0 },
      { text: "Which is greater: 9 or 19?", choices: ["9", "19", "equal", "neither"], answer: 1 },
      { text: "Which is smaller: 30 or 13?", choices: ["13", "30", "equal", "neither"], answer: 0 },
      { text: "Compare: 8 ___ 12", choices: ["greater than", "less than", "equal to", "none"], answer: 1 },
      { text: "Compare: 15 ___ 9", choices: ["greater than", "less than", "equal to", "none"], answer: 0 },
      { text: "Compare: 7 ___ 7", choices: ["greater than", "less than", "equal to", "none"], answer: 2 },
      // Place value
      { text: "What digit is in the tens place of 47?", choices: ["4", "7", "47", "0"], answer: 0 },
      { text: "What digit is in the ones place of 63?", choices: ["6", "3", "63", "0"], answer: 1 },
      { text: "What number is 3 tens and 5 ones?", choices: ["8", "35", "53", "305"], answer: 1 },
      { text: "What number is 4 tens and 0 ones?", choices: ["4", "40", "44", "400"], answer: 1 },
      { text: "How many tens are in 50?", choices: ["1", "5", "10", "50"], answer: 1 },
      { text: "How many ones are in 27?", choices: ["2", "7", "9", "27"], answer: 1 },
      // Shapes
      { text: "How many sides does a triangle have?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "How many sides does a square have?", choices: ["3", "4", "5", "6"], answer: 1 },
      { text: "What shape has no sides?", choices: ["square", "triangle", "circle", "rectangle"], answer: 2 },
      { text: "How many sides does a rectangle have?", choices: ["3", "4", "5", "6"], answer: 1 },
      { text: "How many sides does a pentagon have?", choices: ["4", "5", "6", "7"], answer: 1 },
      { text: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], answer: 1 },
      { text: "How many corners does a triangle have?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "How many corners does a square have?", choices: ["3", "4", "5", "6"], answer: 1 },
      // Time
      { text: "If it is 3 o'clock, what time will it be in 1 hour?", choices: ["2 o'clock", "3:30", "4 o'clock", "5 o'clock"], answer: 2 },
      { text: "How many minutes are in an hour?", choices: ["30", "45", "60", "100"], answer: 2 },
      { text: "How many hours are in a day?", choices: ["12", "20", "24", "30"], answer: 2 },
      { text: "How many days are in a week?", choices: ["5", "6", "7", "10"], answer: 2 },
      // Word problems
      { text: "Sam has 6 apples. He eats 2. How many are left?", choices: ["2", "3", "4", "5"], answer: 2 },
      { text: "Lisa has 4 cats and gets 3 more. How many cats now?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "There are 5 birds. 3 more come. How many now?", choices: ["7", "8", "9", "10"], answer: 1 },
      { text: "Mom baked 12 cookies. We ate 4. How many left?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "There are 10 fish. 3 swim away. How many left?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "Tom has 6 stickers. He gets 6 more. How many now?", choices: ["10", "11", "12", "13"], answer: 2 },
      { text: "There are 4 red apples and 5 green apples. How many in all?", choices: ["8", "9", "10", "11"], answer: 1 },
      { text: "Jane had 15 candies. She gave 5 away. How many left?", choices: ["8", "9", "10", "11"], answer: 2 },
      { text: "There are 7 ducks. 4 more join. How many ducks now?", choices: ["10", "11", "12", "13"], answer: 1 },
      // Doubles and halves
      { text: "Double 4 is...?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "Double 7 is...?", choices: ["12", "13", "14", "15"], answer: 2 },
      { text: "Half of 8 is...?", choices: ["2", "3", "4", "5"], answer: 2 },
      { text: "Half of 10 is...?", choices: ["3", "4", "5", "6"], answer: 2 },
      { text: "Half of 6 is...?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "Half of 20 is...?", choices: ["5", "8", "10", "15"], answer: 2 },
      // Number sequence
      { text: "What number comes after 19?", choices: ["18", "20", "21", "29"], answer: 1 },
      { text: "What number comes before 13?", choices: ["11", "12", "14", "15"], answer: 1 },
      { text: "What comes after 99?", choices: ["100", "101", "98", "110"], answer: 0 },
      { text: "What comes before 50?", choices: ["48", "49", "51", "55"], answer: 1 },
      { text: "What number is between 7 and 9?", choices: ["6", "8", "10", "11"], answer: 1 },
      // Even/odd
      { text: "Is 6 even or odd?", choices: ["even", "odd", "both", "neither"], answer: 0 },
      { text: "Is 9 even or odd?", choices: ["even", "odd", "both", "neither"], answer: 1 },
      { text: "Which number is odd?", choices: ["4", "8", "7", "10"], answer: 2 },
      { text: "Which number is even?", choices: ["3", "5", "8", "11"], answer: 2 },
      // Money
      { text: "How many cents is a nickel?", choices: ["1", "5", "10", "25"], answer: 1 },
      { text: "How many cents is a dime?", choices: ["1", "5", "10", "25"], answer: 2 },
      { text: "How many cents is a penny?", choices: ["1", "5", "10", "25"], answer: 0 },
      { text: "How many cents is a quarter?", choices: ["5", "10", "25", "50"], answer: 2 },
      { text: "Two nickels equal how many cents?", choices: ["5", "10", "15", "20"], answer: 1 },
      // Measurement
      { text: "Which is heaviest?", choices: ["feather", "brick", "paper", "leaf"], answer: 1 },
      { text: "Which is longer: a pencil or a car?", choices: ["pencil", "car", "equal", "both"], answer: 1 },
      { text: "Which is heavier: a feather or a rock?", choices: ["feather", "rock", "equal", "neither"], answer: 1 },
      { text: "We use this tool to measure how long something is.", choices: ["clock", "ruler", "scale", "thermometer"], answer: 1 },
      { text: "We use this tool to measure how heavy something is.", choices: ["clock", "ruler", "scale", "cup"], answer: 2 },
    ],
    reading: [
      // Rhyming
      { text: "Which word rhymes with 'cat'?", choices: ["dog", "hat", "fish", "tree"], answer: 1 },
      { text: "Which word rhymes with 'sun'?", choices: ["moon", "fun", "star", "sky"], answer: 1 },
      { text: "Which word rhymes with 'book'?", choices: ["read", "page", "look", "word"], answer: 2 },
      { text: "Which word rhymes with 'tree'?", choices: ["leaf", "bee", "root", "branch"], answer: 1 },
      { text: "Which word rhymes with 'hat'?", choices: ["dog", "bat", "shoe", "lamp"], answer: 1 },
      { text: "Which word rhymes with 'star'?", choices: ["sun", "car", "moon", "night"], answer: 1 },
      { text: "Which word rhymes with 'big'?", choices: ["small", "pig", "great", "huge"], answer: 1 },
      { text: "Which word rhymes with 'mop'?", choices: ["floor", "top", "broom", "wash"], answer: 1 },
      { text: "Which word rhymes with 'ring'?", choices: ["gold", "king", "bell", "round"], answer: 1 },
      { text: "Which word rhymes with 'mouse'?", choices: ["cat", "house", "rat", "cheese"], answer: 1 },
      { text: "Which word rhymes with 'sand'?", choices: ["beach", "hand", "wave", "shell"], answer: 1 },
      { text: "Which word rhymes with 'cake'?", choices: ["sweet", "bake", "frost", "candle"], answer: 1 },
      { text: "Which word rhymes with 'jump'?", choices: ["leap", "bump", "high", "run"], answer: 1 },
      { text: "Which word rhymes with 'fly'?", choices: ["bird", "sky", "wing", "soar"], answer: 1 },
      { text: "Which word rhymes with 'snow'?", choices: ["cold", "blow", "white", "ice"], answer: 1 },
      // Beginning sounds
      { text: "Which word starts with the same sound as 'ball'?", choices: ["apple", "bear", "cat", "dog"], answer: 1 },
      { text: "Which word starts with the same sound as 'snake'?", choices: ["sun", "tree", "moon", "frog"], answer: 0 },
      { text: "What letter does 'apple' start with?", choices: ["a", "b", "c", "p"], answer: 0 },
      { text: "What letter does 'zebra' start with?", choices: ["x", "y", "z", "a"], answer: 2 },
      { text: "What sound does 'dog' start with?", choices: ["b", "d", "g", "o"], answer: 1 },
      { text: "What sound does 'fish' start with?", choices: ["c", "f", "p", "s"], answer: 1 },
      { text: "What word starts like 'moon'?", choices: ["man", "tree", "book", "fish"], answer: 0 },
      { text: "What word starts like 'pig'?", choices: ["dog", "pen", "cat", "fox"], answer: 1 },
      { text: "What sound does 'sh' make?", choices: ["ssss", "shhh", "ffff", "tttt"], answer: 1 },
      { text: "What sound does 'th' make in 'thumb'?", choices: ["tuh", "th", "fuh", "shh"], answer: 1 },
      // Opposites
      { text: "What is the opposite of 'big'?", choices: ["large", "small", "huge", "tall"], answer: 1 },
      { text: "What is the opposite of 'hot'?", choices: ["warm", "cool", "cold", "wet"], answer: 2 },
      { text: "What is the opposite of 'up'?", choices: ["high", "low", "down", "side"], answer: 2 },
      { text: "What is the opposite of 'happy'?", choices: ["mad", "sad", "tired", "sleepy"], answer: 1 },
      { text: "Opposite of 'fast'?", choices: ["quick", "slow", "speed", "rush"], answer: 1 },
      { text: "Opposite of 'tall'?", choices: ["high", "short", "long", "big"], answer: 1 },
      { text: "Opposite of 'wet'?", choices: ["damp", "dry", "moist", "soaked"], answer: 1 },
      { text: "Opposite of 'open'?", choices: ["wide", "closed", "ajar", "shut"], answer: 1 },
      { text: "Opposite of 'day'?", choices: ["sunny", "morning", "night", "noon"], answer: 2 },
      { text: "Opposite of 'soft'?", choices: ["fluffy", "hard", "smooth", "fuzzy"], answer: 1 },
      { text: "Opposite of 'in'?", choices: ["out", "by", "near", "next"], answer: 0 },
      { text: "Opposite of 'over'?", choices: ["above", "under", "around", "across"], answer: 1 },
      { text: "Opposite of 'old'?", choices: ["aged", "ancient", "new", "used"], answer: 2 },
      { text: "Opposite of 'empty'?", choices: ["full", "lonely", "open", "tall"], answer: 0 },
      // Categories
      { text: "Which is a color?", choices: ["five", "blue", "run", "jump"], answer: 1 },
      { text: "Which is an animal?", choices: ["chair", "rock", "rabbit", "tree"], answer: 2 },
      { text: "Which is a number?", choices: ["seven", "purple", "shoe", "cup"], answer: 0 },
      { text: "Which is a fruit?", choices: ["chair", "apple", "sock", "bus"], answer: 1 },
      { text: "Which is clothing?", choices: ["shoe", "plate", "tree", "fish"], answer: 0 },
      { text: "Which is a vegetable?", choices: ["carrot", "dog", "hat", "car"], answer: 0 },
      { text: "Which is transportation?", choices: ["bus", "banana", "tree", "lamp"], answer: 0 },
      { text: "Which is a body part?", choices: ["arm", "ball", "kite", "soap"], answer: 0 },
      { text: "Which is a tool?", choices: ["bird", "hammer", "moon", "cloud"], answer: 1 },
      { text: "Which is a season?", choices: ["sunny", "summer", "happy", "fast"], answer: 1 },
      // Comprehension
      { text: "If Tom ran fast, how did Tom run?", choices: ["slow", "fast", "loud", "soft"], answer: 1 },
      { text: "The dog is wet. What happened to the dog?", choices: ["it slept", "it got water on it", "it ate", "it ran"], answer: 1 },
      { text: "Sam ate cake. What did Sam eat?", choices: ["pie", "cake", "candy", "bread"], answer: 1 },
      { text: "The cat sat on the mat. Where did the cat sit?", choices: ["on the chair", "on the bed", "on the mat", "on the floor"], answer: 2 },
      { text: "Lily ran to the park. Where did Lily run?", choices: ["to school", "to the park", "to home", "to the store"], answer: 1 },
      { text: "The sun is hot. How is the sun?", choices: ["cold", "warm", "hot", "cool"], answer: 2 },
      { text: "Birds can fly. What can birds do?", choices: ["swim", "fly", "dig", "walk only"], answer: 1 },
      // Word meanings
      { text: "Pick the word that means very small.", choices: ["huge", "tiny", "long", "wide"], answer: 1 },
      { text: "Pick the word that means very fast.", choices: ["slow", "quick", "sleepy", "still"], answer: 1 },
      { text: "Which word means 'a place to sleep'?", choices: ["bed", "chair", "table", "sink"], answer: 0 },
      { text: "If I am cold, what should I wear?", choices: ["shorts", "tank top", "coat", "swimsuit"], answer: 2 },
      { text: "What do you do with a book?", choices: ["eat it", "read it", "kick it", "wear it"], answer: 1 },
      { text: "What is a baby cat called?", choices: ["puppy", "kitten", "cub", "chick"], answer: 1 },
      { text: "What is a baby dog called?", choices: ["puppy", "kitten", "cub", "calf"], answer: 0 },
      { text: "What is a baby cow called?", choices: ["puppy", "kitten", "cub", "calf"], answer: 3 },
      { text: "What is a baby bird called?", choices: ["pup", "kitten", "chick", "calf"], answer: 2 },
      { text: "The word 'tiny' means...", choices: ["very small", "very big", "very fast", "very slow"], answer: 0 },
      { text: "The word 'shout' means...", choices: ["speak loudly", "speak softly", "stay quiet", "whisper"], answer: 0 },
      { text: "The word 'gigantic' means...", choices: ["small", "very large", "fast", "soft"], answer: 1 },
      { text: "The word 'whisper' means...", choices: ["shout", "speak quietly", "sing", "yell"], answer: 1 },
      { text: "The word 'leap' means...", choices: ["sit", "jump", "crawl", "stand"], answer: 1 },
      { text: "The word 'gentle' means...", choices: ["rough", "soft and kind", "loud", "mean"], answer: 1 },
      // Story structure
      { text: "The first part of a story is called...", choices: ["the end", "the beginning", "the middle", "the title"], answer: 1 },
      { text: "The last part of a story is called...", choices: ["the title", "the start", "the end", "the page"], answer: 2 },
      { text: "A 'character' in a story is a...", choices: ["page number", "person or animal", "color", "place"], answer: 1 },
      { text: "The 'setting' is...", choices: ["a person", "where and when it happens", "the ending", "the first word"], answer: 1 },
      // Letters
      { text: "What is the first letter of 'apple'?", choices: ["a", "b", "c", "p"], answer: 0 },
      { text: "What is the last letter of 'cat'?", choices: ["c", "a", "t", "s"], answer: 2 },
      { text: "How many letters are in the word 'sun'?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "How many letters are in 'star'?", choices: ["3", "4", "5", "6"], answer: 1 },
      // Sight words
      { text: "Which is a sight word?", choices: ["the", "blarg", "zoozle", "quibz"], answer: 0 },
      { text: "Which word means 'a question'?", choices: ["ask", "jump", "walk", "run"], answer: 0 },
      { text: "Which word means 'really cold'?", choices: ["warm", "hot", "freezing", "sunny"], answer: 2 },
      { text: "Which word means 'very big'?", choices: ["tiny", "huge", "small", "little"], answer: 1 },
      { text: "Which word means 'very tired'?", choices: ["lively", "exhausted", "fast", "ready"], answer: 1 },
    ],
    spelling: [
      // Correct spelling
      { text: "Which is spelled correctly?", choices: ["dgo", "dog", "dag", "doog"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["kat", "cat", "katt", "cot"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["sun", "son", "sin", "soun"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["moun", "mun", "moon", "mone"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["kar", "carr", "car", "cor"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["hous", "house", "hawse", "houz"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["fish", "fis", "phish", "fich"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["brid", "burd", "bird", "berd"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["frend", "freind", "friend", "freand"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["becuz", "becauz", "because", "becose"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["wuz", "was", "waz", "wos"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["sed", "saed", "said", "sayd"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["plae", "play", "pley", "plei"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["red", "reed", "rede", "ree"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["jump", "jumpe", "jamp", "jumpp"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["lik", "like", "liek", "likke"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["bik", "bike", "biek", "bikke"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["mak", "make", "maek", "mayk"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["wite", "white", "whiet", "whyt"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["foot", "fot", "fute", "fuut"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["nest", "nast", "neast", "nezt"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["cake", "caek", "kake", "caik"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["lov", "love", "luve", "lovv"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["gud", "good", "goud", "goode"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["yu", "yoo", "you", "yoou"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["ar", "are", "arr", "aer"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["thay", "they", "theigh", "thei"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["bal", "ball", "bawl", "bole"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["kum", "come", "cume", "coam"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["hav", "have", "haev", "hae"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["tym", "tyme", "time", "tiem"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["stop", "stp", "stope", "stopp"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["littal", "little", "lital", "littell"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["walk", "wak", "walke", "wolk"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["hapy", "happy", "happie", "happi"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["chear", "chair", "chare", "chaier"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["babi", "baby", "beby", "babee"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["rain", "rane", "raen", "rin"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["ster", "store", "stoor", "stoure"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["muther", "mother", "mothir", "muthar"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["bred", "bread", "brede", "brid"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["stik", "stick", "stike", "stik"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["skoo", "school", "scool", "skool"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["srtar", "star", "stare", "ster"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["nem", "name", "naem", "nayme"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["home", "hom", "hume", "hoam"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["kite", "kit", "kiet", "kyte"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["nose", "nos", "noze", "noase"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["smil", "smile", "smiel", "smyle"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["chare", "share", "shaer", "shar"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["ship", "shp", "sip", "shipp"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["chery", "cherry", "chereee", "cherrie"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["with", "wif", "withh", "wid"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["thingg", "thing", "theng", "thyng"], answer: 1 },
      // Question words
      { text: "Spell the question word for 'what kind':", choices: ["wat", "what", "whaut", "wut"], answer: 1 },
      { text: "Spell the question word for time:", choices: ["wen", "when", "whun", "wenn"], answer: 1 },
      { text: "Spell the word for reasons:", choices: ["wy", "why", "whye", "whi"], answer: 1 },
      { text: "Spell the word for a place:", choices: ["where", "ware", "whayer", "where"], answer: 0 },
      { text: "Spell the word that asks for a person:", choices: ["hoo", "who", "whu", "whoo"], answer: 1 },
      // Fill in vowels
      { text: "Fill in: c_t (a fluffy pet)", choices: ["a", "e", "i", "o"], answer: 0 },
      { text: "Fill in: d_g (a barking pet)", choices: ["a", "e", "i", "o"], answer: 3 },
      { text: "Fill in: b_g (an insect)", choices: ["a", "e", "i", "u"], answer: 3 },
      { text: "Fill in: p_g (an oinking animal)", choices: ["a", "e", "i", "o"], answer: 2 },
      { text: "Fill in: s_n (it shines)", choices: ["a", "e", "i", "u"], answer: 3 },
      { text: "Fill in: m_n (it shines at night, two letters)", choices: ["a", "oo", "i", "u"], answer: 1 },
      // Silent e
      { text: "Which word has a silent 'e'?", choices: ["cat", "cake", "dog", "sun"], answer: 1 },
      { text: "Which word has a silent 'e'?", choices: ["bike", "bug", "fish", "moon"], answer: 0 },
      { text: "Which word has a silent 'e'?", choices: ["hop", "hat", "kite", "run"], answer: 2 },
      // Number words
      { text: "How do you spell 'one more than two'?", choices: ["thre", "three", "thee", "thare"], answer: 1 },
      { text: "How do you spell 'one less than five'?", choices: ["fore", "for", "four", "foor"], answer: 2 },
      { text: "How do you spell 'half of ten'?", choices: ["fiv", "five", "fiev", "fyve"], answer: 1 },
      // Color words
      { text: "How do you spell the color of the sky?", choices: ["bloo", "blu", "blue", "bleu"], answer: 2 },
      { text: "How do you spell the color of grass?", choices: ["grin", "green", "grene", "gren"], answer: 1 },
      { text: "How do you spell the color of snow?", choices: ["wite", "white", "whyte", "whiet"], answer: 1 },
      { text: "How do you spell the color of the sun?", choices: ["yelow", "yellow", "yellou", "yellaw"], answer: 1 },
      { text: "How do you spell the color of an apple?", choices: ["rad", "red", "redd", "raid"], answer: 1 },
      // Family words
      { text: "How do you spell the word for your dad?", choices: ["fathar", "father", "fadher", "fath"], answer: 1 },
      { text: "How do you spell the word for your sister or brother's child?", choices: ["neece", "niece", "nese", "nees"], answer: 1 },
      { text: "How do you spell the word for grandma?", choices: ["grendma", "grandma", "granma", "gramda"], answer: 1 },
    ],
    grammar: [
      // Parts of speech
      { text: "A noun is a...", choices: ["person, place, or thing", "action word", "color", "feeling"], answer: 0 },
      { text: "A verb is a...", choices: ["thing", "action word", "name", "color"], answer: 1 },
      { text: "Which word is a noun?", choices: ["run", "happy", "dog", "quickly"], answer: 2 },
      { text: "Which word is a verb?", choices: ["car", "jump", "blue", "sleepy"], answer: 1 },
      { text: "Which word is a noun?", choices: ["sing", "tree", "fast", "loud"], answer: 1 },
      { text: "Which word is a verb?", choices: ["happy", "house", "run", "red"], answer: 2 },
      { text: "Which is a noun?", choices: ["sing", "table", "fast", "blue"], answer: 1 },
      { text: "Which is a noun?", choices: ["jump", "happy", "dog", "run"], answer: 2 },
      { text: "Which is a noun?", choices: ["red", "mom", "big", "sleep"], answer: 1 },
      { text: "Which is a noun?", choices: ["sleep", "school", "hot", "cold"], answer: 1 },
      { text: "Which is a noun?", choices: ["book", "write", "smart", "quick"], answer: 0 },
      { text: "Which is a verb?", choices: ["cat", "run", "big", "red"], answer: 1 },
      { text: "Which is a verb?", choices: ["chair", "walk", "soft", "blue"], answer: 1 },
      { text: "Which is a verb?", choices: ["dog", "swim", "happy", "small"], answer: 1 },
      { text: "Which is a verb?", choices: ["book", "read", "smart", "fast"], answer: 1 },
      { text: "Which is a verb?", choices: ["sky", "fly", "blue", "bird"], answer: 1 },
      { text: "Which word names a place?", choices: ["jump", "park", "happy", "loud"], answer: 1 },
      { text: "Which names a place?", choices: ["park", "run", "soft", "happy"], answer: 0 },
      { text: "Which names a person?", choices: ["kick", "teacher", "blue", "table"], answer: 1 },
      // Adjectives
      { text: "Which word describes how something looks or feels?", choices: ["cat", "big", "run", "school"], answer: 1 },
      { text: "Which describes?", choices: ["happy", "dog", "run", "jump"], answer: 0 },
      { text: "In 'a red ball', the word 'red' tells you what about the ball?", choices: ["its size", "its color", "its name", "what it does"], answer: 1 },
      { text: "In 'a soft pillow', 'soft' tells you what?", choices: ["how it feels", "where it is", "what it does", "its name"], answer: 0 },
      { text: "Pick the describing word in 'tall man'.", choices: ["man", "tall", "the", "a"], answer: 1 },
      // Identifying parts of sentence
      { text: "Pick the action word in: 'The bird flies.'", choices: ["The", "bird", "flies", "the"], answer: 2 },
      { text: "Pick the action word in: 'I eat apples.'", choices: ["I", "eat", "apples", "the"], answer: 1 },
      { text: "Pick the action in: 'The girl sings.'", choices: ["girl", "the", "sings", "a"], answer: 2 },
      { text: "Pick the action in: 'My dog barks.'", choices: ["my", "dog", "barks", "the"], answer: 2 },
      { text: "Pick the action in: 'Birds fly.'", choices: ["birds", "fly", "the", "a"], answer: 1 },
      // Articles
      { text: "We say '___ apple', not 'a apple'.", choices: ["an", "the", "this", "that"], answer: 0 },
      { text: "We say '___ book'.", choices: ["a", "an", "and", "ax"], answer: 0 },
      { text: "We say '___ elephant'.", choices: ["a", "an", "the only", "or"], answer: 1 },
      { text: "We say '___ orange'.", choices: ["a", "an", "ten", "is"], answer: 1 },
      { text: "We say '___ umbrella'.", choices: ["a", "an", "and", "the only"], answer: 1 },
      // Sentence types
      { text: "Sentences begin with what kind of letter?", choices: ["capital", "lowercase", "any letter", "a number"], answer: 0 },
      { text: "Sentences end with...", choices: ["a letter", "a punctuation mark", "a number", "nothing"], answer: 1 },
      { text: "Which is a complete sentence?", choices: ["The cat.", "Ran fast.", "The cat ran fast.", "Fast cat."], answer: 2 },
      { text: "Which is a complete sentence?", choices: ["My dog", "Barks loud.", "My dog barks.", "Dog loud"], answer: 2 },
      { text: "Which is a question sentence?", choices: ["I am tall.", "Are you tall?", "I am tall!", "Tall am I."], answer: 1 },
      { text: "Which is a question?", choices: ["I am happy.", "Are you sad?", "Stop!", "Run."], answer: 1 },
      { text: "Which is exclaiming?", choices: ["Hi.", "How are you?", "Yay!", "Sit."], answer: 2 },
      { text: "Pick the command:", choices: ["The door is closed.", "Is the door closed?", "Close the door.", "Doors close."], answer: 2 },
      { text: "What punctuation ends an exciting sentence?", choices: [".", "?", "!", ","], answer: 2 },
      { text: "What punctuation ends a question?", choices: [".", "?", "!", ","], answer: 1 },
      { text: "What punctuation ends a telling sentence?", choices: [".", "?", "!", ","], answer: 0 },
      // Plurals
      { text: "What is the plural of 'cat'?", choices: ["cat", "cats", "cates", "caties"], answer: 1 },
      { text: "What is the plural of 'box'?", choices: ["boxs", "boxes", "boxies", "box"], answer: 1 },
      { text: "What is the plural of 'baby'?", choices: ["babys", "babes", "babies", "babbies"], answer: 2 },
      { text: "Which means more than one mouse?", choices: ["mouses", "mice", "mooses", "mousies"], answer: 1 },
      { text: "What is the plural of 'dog'?", choices: ["dogs", "doges", "dogees", "dogis"], answer: 0 },
      { text: "What is the plural of 'fish'?", choices: ["fish", "fishs", "fishes", "fisha"], answer: 0 },
      { text: "What is the plural of 'kid'?", choices: ["kid", "kids", "kides", "kiddies"], answer: 1 },
      { text: "What is the plural of 'foot'?", choices: ["foots", "feets", "feet", "footses"], answer: 2 },
      { text: "What is the plural of 'man'?", choices: ["mans", "mens", "men", "manses"], answer: 2 },
      { text: "What is the plural of 'child'?", choices: ["childs", "childes", "children", "childies"], answer: 2 },
      { text: "What is the plural of 'tooth'?", choices: ["tooths", "teeth", "teeths", "toothes"], answer: 1 },
      // Verb agreement
      { text: "Should we say 'I ___ happy'?", choices: ["am", "is", "are", "be"], answer: 0 },
      { text: "Should we say 'She ___ running'?", choices: ["am", "is", "are", "be"], answer: 1 },
      { text: "Should we say 'They ___ playing'?", choices: ["am", "is", "are", "be"], answer: 2 },
      { text: "Should we say 'We ___ friends'?", choices: ["am", "is", "are", "be"], answer: 2 },
      { text: "Should we say 'He ___ tall'?", choices: ["am", "is", "are", "be"], answer: 1 },
      // Pronouns
      { text: "We use ___ to talk about ourselves.", choices: ["I", "you", "she", "he"], answer: 0 },
      { text: "We use ___ when talking to someone.", choices: ["I", "you", "he", "she"], answer: 1 },
      { text: "We use 'she' for a...", choices: ["girl", "boy", "group", "thing"], answer: 0 },
      { text: "We use 'he' for a...", choices: ["boy", "girl", "group", "thing"], answer: 0 },
      { text: "We use 'it' for a...", choices: ["girl", "boy", "thing", "group of people"], answer: 2 },
      { text: "We use 'they' for...", choices: ["one person", "more than one", "one thing", "no one"], answer: 1 },
      // Capitalization
      { text: "Which sentence is correct?", choices: ["the dog runs.", "The dog runs.", "the Dog Runs", "THE DOG RUNS"], answer: 1 },
      { text: "Capitalize names. Which is right?", choices: ["my friend sam", "My friend Sam", "my Friend sam", "MY friend sam"], answer: 1 },
      { text: "Which is correct?", choices: ["i am sam.", "I am Sam.", "i Am Sam.", "I am sam"], answer: 1 },
      { text: "Which is correct?", choices: ["my mom is here.", "My mom is here.", "My Mom Is Here.", "my mom is Here."], answer: 1 },
      // Contractions
      { text: "'Don't' is short for...", choices: ["do nut", "do not", "doing not", "do now"], answer: 1 },
      { text: "'Can't' is short for...", choices: ["can to", "can not", "could not", "cane not"], answer: 1 },
      { text: "'It's' is short for...", choices: ["it has", "it was", "it is", "it as"], answer: 2 },
      { text: "'I'm' is short for...", choices: ["I am", "I mean", "I might", "I make"], answer: 0 },
      { text: "'You're' is short for...", choices: ["your", "you are", "you were", "your own"], answer: 1 },
      // Time / sequence
      { text: "Which word means 'one day after today'?", choices: ["today", "tomorrow", "yesterday", "next week"], answer: 1 },
      { text: "Which word means 'one day before today'?", choices: ["tomorrow", "yesterday", "today", "later"], answer: 1 },
      // Asking words
      { text: "To ask about a place, we use the word...", choices: ["where", "when", "why", "what"], answer: 0 },
      { text: "To ask about a time, we use the word...", choices: ["where", "when", "why", "who"], answer: 1 },
      { text: "To ask about a person, we use the word...", choices: ["why", "what", "where", "who"], answer: 3 },
      { text: "To ask about a reason, we use the word...", choices: ["where", "when", "why", "what"], answer: 2 },
    ],
  },

  // ================================================
  // GRADE 4 — Owen (just finished 4th grade)
  // ================================================
  grade4: {
    math: [
      // Multiplication
      { text: "What is 6 × 7?", choices: ["40", "42", "48", "56"], answer: 1 },
      { text: "What is 8 × 8?", choices: ["56", "60", "64", "72"], answer: 2 },
      { text: "What is 9 × 6?", choices: ["48", "54", "56", "63"], answer: 1 },
      { text: "What is 11 × 7?", choices: ["63", "70", "77", "84"], answer: 2 },
      { text: "What is 12 × 4?", choices: ["44", "46", "48", "52"], answer: 2 },
      { text: "What is 13 × 5?", choices: ["55", "60", "65", "75"], answer: 2 },
      { text: "What is 25 × 4?", choices: ["80", "90", "100", "120"], answer: 2 },
      { text: "What is 18 × 3?", choices: ["48", "52", "54", "60"], answer: 2 },
      { text: "What is 14 × 6?", choices: ["72", "78", "84", "96"], answer: 2 },
      { text: "What is 22 × 5?", choices: ["100", "105", "110", "115"], answer: 2 },
      { text: "What is 16 × 8?", choices: ["112", "124", "128", "136"], answer: 2 },
      { text: "What is 100 × 24?", choices: ["240", "2400", "24000", "200"], answer: 1 },
      { text: "What is 24 × 6?", choices: ["124", "134", "144", "154"], answer: 2 },
      { text: "What is 15 × 12?", choices: ["170", "180", "190", "200"], answer: 1 },
      { text: "What is 7 × 8?", choices: ["54", "56", "58", "64"], answer: 1 },
      { text: "What is 9 × 9?", choices: ["72", "79", "81", "91"], answer: 2 },
      { text: "What is 12 × 11?", choices: ["121", "122", "132", "144"], answer: 2 },
      { text: "What is 234 × 2?", choices: ["434", "458", "468", "478"], answer: 2 },
      { text: "What is 125 × 8?", choices: ["900", "1000", "1100", "1250"], answer: 1 },
      { text: "What is 47 × 30?", choices: ["1170", "1410", "1470", "1500"], answer: 1 },
      { text: "What is 156 × 4?", choices: ["604", "614", "624", "634"], answer: 2 },
      // Division
      { text: "What is 144 ÷ 12?", choices: ["10", "11", "12", "13"], answer: 2 },
      { text: "What is 96 ÷ 8?", choices: ["10", "11", "12", "13"], answer: 2 },
      { text: "What is 63 ÷ 9?", choices: ["6", "7", "8", "9"], answer: 1 },
      { text: "What is 84 ÷ 4?", choices: ["20", "21", "22", "24"], answer: 1 },
      { text: "What is 72 ÷ 6?", choices: ["10", "11", "12", "13"], answer: 2 },
      { text: "What is 132 ÷ 11?", choices: ["11", "12", "13", "14"], answer: 1 },
      { text: "What is 100 ÷ 4?", choices: ["20", "22", "25", "28"], answer: 2 },
      { text: "What is 120 ÷ 5?", choices: ["20", "22", "24", "25"], answer: 2 },
      { text: "What is 56 ÷ 7?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "What is 81 ÷ 9?", choices: ["6", "7", "8", "9"], answer: 3 },
      { text: "What is 144 ÷ 6?", choices: ["22", "23", "24", "25"], answer: 2 },
      { text: "What is 90 ÷ 10?", choices: ["8", "9", "10", "11"], answer: 1 },
      { text: "What is 175 ÷ 5?", choices: ["33", "34", "35", "36"], answer: 2 },
      // Addition/subtraction
      { text: "What is 357 + 248?", choices: ["595", "605", "615", "705"], answer: 1 },
      { text: "What is 902 - 387?", choices: ["505", "515", "525", "615"], answer: 1 },
      { text: "What is 1,234 + 5,678?", choices: ["6,812", "6,912", "7,012", "7,112"], answer: 1 },
      { text: "What is 1,000 - 367?", choices: ["623", "633", "643", "667"], answer: 1 },
      // Fractions
      { text: "What is 1/2 + 1/4?", choices: ["1/6", "2/6", "3/4", "1/4"], answer: 2 },
      { text: "What is 3/4 - 1/4?", choices: ["1/4", "1/2", "3/4", "1/8"], answer: 1 },
      { text: "Which fraction is equal to 1/2?", choices: ["2/3", "3/6", "2/5", "4/5"], answer: 1 },
      { text: "What is 1/3 + 1/3?", choices: ["1/3", "2/3", "2/6", "1/6"], answer: 1 },
      { text: "What is 5/8 - 2/8?", choices: ["2/8", "3/8", "4/8", "7/8"], answer: 1 },
      { text: "What is 1/2 of 10?", choices: ["3", "4", "5", "6"], answer: 2 },
      { text: "What is 1/4 of 20?", choices: ["4", "5", "6", "8"], answer: 1 },
      { text: "What is 1/3 of 9?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "Which fraction is bigger: 1/2 or 1/4?", choices: ["1/2", "1/4", "equal", "neither"], answer: 0 },
      { text: "Which fraction is smaller: 3/4 or 2/3?", choices: ["3/4", "2/3", "equal", "neither"], answer: 1 },
      { text: "Convert 4/2 to a whole number.", choices: ["1", "2", "3", "4"], answer: 1 },
      { text: "Convert 6/3 to a whole number.", choices: ["1", "2", "3", "6"], answer: 1 },
      { text: "Which fraction equals 1/3?", choices: ["1/6", "2/6", "3/6", "4/6"], answer: 1 },
      { text: "Which fraction equals 3/4?", choices: ["3/8", "4/8", "6/8", "7/8"], answer: 2 },
      { text: "A pizza has 8 slices. If you eat 3, what fraction is left?", choices: ["3/8", "5/8", "3/5", "8/3"], answer: 1 },
      // Decimals
      { text: "Which is greater: 0.5 or 0.45?", choices: ["0.5", "0.45", "equal", "neither"], answer: 0 },
      { text: "What is 0.5 + 0.5?", choices: ["0.10", "0.5", "1.0", "1.5"], answer: 2 },
      { text: "What is 1.2 + 0.8?", choices: ["1.0", "1.8", "2.0", "2.8"], answer: 2 },
      { text: "What is 3.5 - 1.2?", choices: ["1.3", "2.3", "2.7", "3.3"], answer: 1 },
      { text: "What is 0.1 + 0.9?", choices: ["0.10", "0.9", "1.0", "1.9"], answer: 2 },
      { text: "What is 0.25 + 0.25?", choices: ["0.4", "0.5", "0.6", "0.50"], answer: 1 },
      { text: "Which is bigger: 0.7 or 0.65?", choices: ["0.7", "0.65", "equal", "neither"], answer: 0 },
      { text: "Which decimal equals 1/2?", choices: ["0.2", "0.25", "0.5", "0.75"], answer: 2 },
      { text: "Which decimal equals 1/4?", choices: ["0.14", "0.25", "0.4", "0.5"], answer: 1 },
      // Percentages
      { text: "What is 25% of 100?", choices: ["20", "25", "50", "75"], answer: 1 },
      { text: "What is 50% of 80?", choices: ["20", "30", "40", "50"], answer: 2 },
      { text: "What is 10% of 200?", choices: ["10", "20", "30", "100"], answer: 1 },
      { text: "What is 100% of 75?", choices: ["50", "75", "100", "150"], answer: 1 },
      // Rounding
      { text: "Round 487 to the nearest 100.", choices: ["400", "480", "490", "500"], answer: 3 },
      { text: "Round 6,342 to the nearest 1,000.", choices: ["5,000", "6,000", "6,500", "7,000"], answer: 1 },
      { text: "Round 234 to the nearest 10.", choices: ["220", "230", "240", "300"], answer: 1 },
      { text: "Round 567 to the nearest 100.", choices: ["500", "560", "570", "600"], answer: 3 },
      { text: "Round 1,234 to the nearest 1,000.", choices: ["1,000", "1,200", "1,500", "2,000"], answer: 0 },
      { text: "Round 89 to the nearest 10.", choices: ["80", "85", "90", "100"], answer: 2 },
      // Place value
      { text: "What digit is in the hundreds place of 4,287?", choices: ["4", "2", "8", "7"], answer: 1 },
      { text: "What digit is in the thousands place of 5,679?", choices: ["5", "6", "7", "9"], answer: 0 },
      { text: "What number has 6 thousands, 4 hundreds, 2 tens, and 8 ones?", choices: ["6,248", "6,428", "6,482", "8,624"], answer: 1 },
      // Geometry
      { text: "What is the area of a rectangle 8 cm long and 5 cm wide?", choices: ["13 cm²", "26 cm²", "40 cm²", "45 cm²"], answer: 2 },
      { text: "What is the perimeter of a square with side 7?", choices: ["14", "21", "28", "49"], answer: 2 },
      { text: "What is the area of a square with side 6?", choices: ["12", "24", "30", "36"], answer: 3 },
      { text: "What is the perimeter of a rectangle 5 by 3?", choices: ["8", "15", "16", "30"], answer: 2 },
      { text: "A right angle measures how many degrees?", choices: ["45", "60", "90", "180"], answer: 2 },
      { text: "A straight angle measures how many degrees?", choices: ["90", "120", "180", "360"], answer: 2 },
      { text: "How many degrees in a full circle?", choices: ["90", "180", "270", "360"], answer: 3 },
      { text: "A triangle with 3 equal sides is called...?", choices: ["scalene", "isosceles", "equilateral", "right"], answer: 2 },
      { text: "A triangle with one right angle is called...?", choices: ["acute", "right triangle", "obtuse", "equilateral"], answer: 1 },
      { text: "Which angle is greater than 90°?", choices: ["acute", "right", "obtuse", "straight"], answer: 2 },
      { text: "An angle less than 90° is called...?", choices: ["acute", "right", "obtuse", "straight"], answer: 0 },
      // Time
      { text: "How many minutes in 2 hours?", choices: ["60", "100", "120", "150"], answer: 2 },
      { text: "How many seconds in 3 minutes?", choices: ["120", "150", "180", "210"], answer: 2 },
      { text: "If a movie starts at 4:15 and ends at 6:00, how long is it?", choices: ["1 hr 30 min", "1 hr 45 min", "2 hr", "2 hr 15 min"], answer: 1 },
      { text: "How many minutes in 3 hours?", choices: ["120", "150", "180", "210"], answer: 2 },
      { text: "How many seconds in 5 minutes?", choices: ["200", "250", "300", "500"], answer: 2 },
      { text: "How many days in 4 weeks?", choices: ["21", "24", "28", "30"], answer: 2 },
      { text: "How many months in 2 years?", choices: ["12", "18", "24", "36"], answer: 2 },
      // Measurement
      { text: "Convert 3 feet to inches.", choices: ["12", "24", "36", "48"], answer: 2 },
      { text: "How many ounces in a pound?", choices: ["8", "12", "16", "32"], answer: 2 },
      { text: "How many inches in a foot?", choices: ["10", "12", "16", "24"], answer: 1 },
      { text: "How many feet in a yard?", choices: ["2", "3", "4", "5"], answer: 1 },
      { text: "How many centimeters in a meter?", choices: ["10", "100", "1000", "10000"], answer: 1 },
      // Prime / factors
      { text: "Which is a prime number?", choices: ["4", "6", "9", "11"], answer: 3 },
      { text: "Which is NOT a prime number?", choices: ["3", "5", "9", "7"], answer: 2 },
      { text: "Which is a factor of 12?", choices: ["5", "4", "7", "9"], answer: 1 },
      { text: "Which is a factor of 20?", choices: ["3", "6", "8", "10"], answer: 3 },
      { text: "What is the greatest common factor of 8 and 12?", choices: ["2", "4", "6", "8"], answer: 1 },
      // Patterns
      { text: "Next in pattern: 3, 6, 12, 24, ?", choices: ["36", "42", "48", "72"], answer: 2 },
      { text: "Next in pattern: 5, 10, 20, 40, ?", choices: ["50", "60", "70", "80"], answer: 3 },
      { text: "Next in pattern: 1, 4, 9, 16, ?", choices: ["20", "23", "25", "30"], answer: 2 },
      // Word problems
      { text: "A box has 6 rows of 9 candies. How many candies total?", choices: ["45", "54", "63", "69"], answer: 1 },
      { text: "If 4 friends share 32 cookies equally, how many each?", choices: ["6", "7", "8", "9"], answer: 2 },
      { text: "A pizza has 8 slices. 4 people share equally. How many slices each?", choices: ["1", "2", "3", "4"], answer: 1 },
      { text: "A box holds 12 cookies. 5 boxes have how many cookies?", choices: ["50", "55", "60", "65"], answer: 2 },
      { text: "Tom has 24 marbles. He gives 1/3 away. How many did he give?", choices: ["6", "8", "10", "12"], answer: 1 },
      { text: "A train travels 60 mph for 2 hours. How many miles?", choices: ["30", "60", "120", "180"], answer: 2 },
      { text: "5 boxes have 24 books each. How many books total?", choices: ["100", "110", "120", "144"], answer: 2 },
      { text: "If pencils cost 25 cents each, what do 4 pencils cost?", choices: ["75 cents", "$1.00", "$1.25", "$2.00"], answer: 1 },
      // Negative numbers
      { text: "What is 5 - 8?", choices: ["-3", "3", "-13", "13"], answer: 0 },
      { text: "What is -2 + 5?", choices: ["-3", "3", "-7", "7"], answer: 1 },
      { text: "What is 0 - 4?", choices: ["-4", "4", "-44", "0"], answer: 0 },
    ],
    reading: [
      // Vocabulary
      { text: "What does 'enormous' mean?", choices: ["tiny", "very big", "fast", "smelly"], answer: 1 },
      { text: "What does 'ancient' mean?", choices: ["new", "very old", "fast", "loud"], answer: 1 },
      { text: "What does 'cautious' mean?", choices: ["careful", "careless", "loud", "happy"], answer: 0 },
      { text: "What does 'frequent' mean?", choices: ["rare", "happening often", "lost", "broken"], answer: 1 },
      { text: "What does 'reluctant' mean?", choices: ["eager", "unwilling", "happy", "fast"], answer: 1 },
      { text: "What does 'persistent' mean?", choices: ["giving up", "not giving up", "lazy", "quick"], answer: 1 },
      { text: "What does 'devastated' mean?", choices: ["thrilled", "very upset", "tired", "confused"], answer: 1 },
      { text: "What does 'generous' mean?", choices: ["selfish", "willing to give", "rude", "shy"], answer: 1 },
      { text: "What does 'envious' mean?", choices: ["proud", "jealous", "humble", "thankful"], answer: 1 },
      { text: "What does 'curious' mean?", choices: ["bored", "wanting to learn", "tired", "scared"], answer: 1 },
      { text: "What does 'enthusiastic' mean?", choices: ["uninterested", "very excited", "calm", "sad"], answer: 1 },
      { text: "What does 'observant' mean?", choices: ["careless", "noticing details", "loud", "shy"], answer: 1 },
      // Synonyms/antonyms
      { text: "What is a synonym of 'happy'?", choices: ["sad", "joyful", "tired", "angry"], answer: 1 },
      { text: "What is an antonym of 'difficult'?", choices: ["hard", "tricky", "easy", "tough"], answer: 2 },
      { text: "Which word means 'to make smaller'?", choices: ["enlarge", "shrink", "stretch", "build"], answer: 1 },
      { text: "Which word means 'to praise'?", choices: ["scold", "compliment", "ignore", "hide"], answer: 1 },
      { text: "Synonym of 'fast'?", choices: ["slow", "swift", "lazy", "still"], answer: 1 },
      { text: "Synonym of 'angry'?", choices: ["calm", "furious", "happy", "kind"], answer: 1 },
      { text: "Antonym of 'bright'?", choices: ["light", "shiny", "dim", "sunny"], answer: 2 },
      { text: "Antonym of 'brave'?", choices: ["bold", "fearful", "strong", "tough"], answer: 1 },
      // Context clues
      { text: "Context: 'The dog was famished, so he gobbled his food.' What does 'famished' mean?", choices: ["sleepy", "full", "very hungry", "scared"], answer: 2 },
      { text: "Context: 'The fragile vase shattered when it fell.' What does 'fragile' mean?", choices: ["strong", "easily broken", "old", "tall"], answer: 1 },
      { text: "Context: 'The mountain was so towering, I could barely see the top.' What does 'towering' mean?", choices: ["short", "very tall", "rocky", "snowy"], answer: 1 },
      { text: "Context: 'She was cheerful, smiling all day.' What does 'cheerful' mean?", choices: ["sad", "happy", "quiet", "tired"], answer: 1 },
      { text: "Context: 'The puppy was adorable, so cute it made everyone smile.' What does 'adorable' mean?", choices: ["ugly", "very cute", "scary", "loud"], answer: 1 },
      // Figurative language
      { text: "'The stars danced in the sky' is an example of...?", choices: ["simile", "personification", "hyperbole", "metaphor"], answer: 1 },
      { text: "'Her hair was as black as night' is an example of...?", choices: ["simile", "personification", "hyperbole", "metaphor"], answer: 0 },
      { text: "'I'm so hungry I could eat a horse' is...?", choices: ["simile", "personification", "hyperbole", "metaphor"], answer: 2 },
      { text: "'Time is money' is an example of...?", choices: ["simile", "personification", "hyperbole", "metaphor"], answer: 3 },
      { text: "'Peter Piper picked a peck of pickled peppers' is...?", choices: ["simile", "alliteration", "hyperbole", "metaphor"], answer: 1 },
      { text: "A simile compares two things using...?", choices: ["only nouns", "'like' or 'as'", "numbers", "questions"], answer: 1 },
      { text: "'Her smile was as bright as the sun' is a...?", choices: ["fact", "metaphor", "simile", "rhyme"], answer: 2 },
      { text: "Personification gives ___ qualities to non-human things.", choices: ["alien", "human", "robotic", "weird"], answer: 1 },
      // Main idea / details
      { text: "What is the main idea of a paragraph?", choices: ["the title", "a detail", "what it's mostly about", "the last word"], answer: 2 },
      { text: "When you 'infer' from a text, you...", choices: ["copy it", "use clues to figure it out", "ignore it", "read it loudly"], answer: 1 },
      { text: "Details in a paragraph support the...?", choices: ["title", "main idea", "ending", "author"], answer: 1 },
      { text: "A topic sentence usually appears at...?", choices: ["the end", "the beginning", "the middle only", "any random place"], answer: 1 },
      // Inference
      { text: "If the story says 'her eyes filled with tears,' she probably feels...?", choices: ["excited", "sad", "hungry", "fast"], answer: 1 },
      { text: "If a character is shivering and rubbing arms, they probably feel...?", choices: ["hot", "cold", "happy", "tired"], answer: 1 },
      { text: "If a character is throwing a party with cake, they're probably...?", choices: ["sad", "angry", "celebrating", "sleeping"], answer: 2 },
      { text: "If you see clouds and lightning, you can infer...?", choices: ["it's sunny", "it might storm", "it's snowing", "it's calm"], answer: 1 },
      // Story elements
      { text: "A 'character' in a story is a...?", choices: ["person or animal in it", "type of paper", "color", "place"], answer: 0 },
      { text: "The 'setting' of a story is the...?", choices: ["main person", "where and when it happens", "ending", "first word"], answer: 1 },
      { text: "The 'plot' of a story is the...?", choices: ["place", "events that happen", "title", "author"], answer: 1 },
      { text: "The 'protagonist' is the...?", choices: ["villain", "main character", "narrator", "author"], answer: 1 },
      { text: "The 'antagonist' is the...?", choices: ["main character", "villain or opponent", "setting", "author"], answer: 1 },
      { text: "The 'climax' of a story is...?", choices: ["the beginning", "the most exciting part", "the boring part", "the title"], answer: 1 },
      { text: "The 'resolution' is...?", choices: ["the start", "the problem", "how the story ends", "the title"], answer: 2 },
      // Cause/effect
      { text: "'It rained, so the picnic was canceled.' What's the cause?", choices: ["the rain", "the picnic", "the day", "the food"], answer: 0 },
      { text: "'I forgot my umbrella and got soaked.' What's the effect?", choices: ["got soaked", "forgot umbrella", "rain", "walking"], answer: 0 },
      // Fact vs opinion
      { text: "Which is a fact?", choices: ["Pizza tastes best", "Water freezes at 32°F", "Blue is prettiest", "Math is fun"], answer: 1 },
      { text: "Which is an opinion?", choices: ["A week has 7 days", "Earth has 1 moon", "Chocolate is the best", "Birds lay eggs"], answer: 2 },
      { text: "'Dogs are mammals.' Fact or opinion?", choices: ["fact", "opinion", "both", "neither"], answer: 0 },
      { text: "'Dogs are the best pets.' Fact or opinion?", choices: ["fact", "opinion", "both", "neither"], answer: 1 },
      { text: "'The Earth is round.' Fact or opinion?", choices: ["fact", "opinion", "both", "neither"], answer: 0 },
      { text: "'Chocolate ice cream is delicious.' Fact or opinion?", choices: ["fact", "opinion", "both", "neither"], answer: 1 },
      // Author's purpose
      { text: "An author's purpose can be to...?", choices: ["only entertain", "inform, persuade, or entertain", "only inform", "only persuade"], answer: 1 },
      { text: "If an author writes to convince you to do something, the purpose is...?", choices: ["entertain", "inform", "persuade", "describe"], answer: 2 },
      { text: "If an author writes to teach facts, the purpose is...?", choices: ["entertain", "inform", "persuade", "lie"], answer: 1 },
      // Genres
      { text: "A story about a brave knight and a dragon is what genre?", choices: ["nonfiction", "biography", "fantasy", "news"], answer: 2 },
      { text: "A story explaining how a volcano works is...?", choices: ["fantasy", "fiction", "nonfiction", "poetry"], answer: 2 },
      { text: "A poem with rhyme and rhythm is...?", choices: ["essay", "biography", "poetry", "novel"], answer: 2 },
      { text: "A book about someone's life is a...?", choices: ["fantasy", "biography", "poetry", "comic"], answer: 1 },
      // Prefixes/suffixes
      { text: "What does the prefix 're-' usually mean?", choices: ["not", "again", "before", "after"], answer: 1 },
      { text: "What does the prefix 'un-' usually mean?", choices: ["again", "not", "with", "before"], answer: 1 },
      { text: "What does the suffix '-less' mean?", choices: ["full of", "without", "before", "after"], answer: 1 },
      { text: "What does 'unhappy' mean?", choices: ["very happy", "not happy", "happy again", "always happy"], answer: 1 },
      { text: "What does 'rewrite' mean?", choices: ["write before", "not write", "write again", "right side"], answer: 2 },
      { text: "What does 'pre-' usually mean?", choices: ["after", "before", "during", "instead of"], answer: 1 },
      { text: "What does 'mis-' usually mean?", choices: ["wrong", "right", "before", "after"], answer: 0 },
      { text: "What does 'dis-' usually mean?", choices: ["with", "not / opposite", "before", "again"], answer: 1 },
      { text: "What does 'tele-' usually mean?", choices: ["small", "far / distance", "near", "many"], answer: 1 },
      { text: "What does '-ful' usually mean?", choices: ["without", "full of", "before", "again"], answer: 1 },
      { text: "What does '-able' usually mean?", choices: ["can be done", "cannot", "before", "again"], answer: 0 },
      // Root words
      { text: "What is the root of 'unhappy'?", choices: ["un", "happy", "happi", "py"], answer: 1 },
      { text: "What is the root of 'helpful'?", choices: ["help", "ful", "elp", "lpful"], answer: 0 },
      { text: "What is the root of 'replay'?", choices: ["re", "play", "ay", "rep"], answer: 1 },
      { text: "What is the root of 'unfair'?", choices: ["un", "fair", "air", "unf"], answer: 1 },
      // Reading strategies
      { text: "When you guess what happens next, you are...?", choices: ["predicting", "summarizing", "skipping", "questioning"], answer: 0 },
      { text: "When you tell the main parts of a story briefly, you are...?", choices: ["predicting", "summarizing", "questioning", "rhyming"], answer: 1 },
      { text: "When you connect a story to your own life, you're...?", choices: ["predicting", "summarizing", "making a connection", "rhyming"], answer: 2 },
      // Text features
      { text: "A 'caption' is...?", choices: ["the title", "text describing a picture", "the index", "a footnote"], answer: 1 },
      { text: "A 'glossary' contains...?", choices: ["the table of contents", "the cover art", "word definitions", "the author bio"], answer: 2 },
      { text: "A 'heading' in a book is...?", choices: ["a title of a section", "a picture", "a footnote", "an index entry"], answer: 0 },
    ],
    spelling: [
      // Common misspellings
      { text: "Which is spelled correctly?", choices: ["beleive", "believe", "belive", "beleeve"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["recieve", "receive", "receeve", "reciev"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["seperate", "seperete", "separate", "separete"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["definately", "definitely", "definitley", "definatly"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["necessary", "neccessary", "nesessary", "neccesary"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["embarass", "embarrass", "embarras", "embaras"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["beautifull", "beutiful", "beautiful", "beautyful"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["different", "diffrent", "diferent", "diffirent"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["because", "becuase", "becouse", "becase"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["friend", "freind", "frend", "friand"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["tomorow", "tomorrow", "tommorow", "tommorrow"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["yesterdy", "yesterday", "yesteday", "yesterdai"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["tonite", "tonight", "tonigth", "toonight"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["lybrary", "library", "libary", "libray"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["febuary", "february", "februry", "februery"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["wensday", "wednesday", "wendsday", "wedensday"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["shedule", "schedule", "scedule", "scheduel"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["govenment", "government", "govermnent", "goverment"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["enviroment", "environment", "enviornment", "enviromint"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["truely", "truly", "trully", "truley"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["happend", "happenned", "happened", "hapened"], answer: 2 },
      { text: "Which is spelled correctly?", choices: ["untill", "until", "untile", "untell"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["bizness", "business", "bisness", "busness"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["stomack", "stomach", "stomich", "stomack"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["pizza", "pisza", "pitza", "peetza"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["vegtable", "vegetable", "vegitable", "vegetbal"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["aniversary", "anniversary", "anniverary", "anniversery"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["rhyme", "rime", "ryhme", "rhime"], answer: 0 },
      { text: "Which is spelled correctly?", choices: ["rythm", "rhythm", "rythym", "rhythym"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["ocasion", "occasion", "occassion", "ocassion"], answer: 1 },
      { text: "Which is spelled correctly?", choices: ["tomato", "tomatoe", "tamato", "tomatto"], answer: 0 },
      // Homophones
      { text: "Homophone: ___ are going to the park.", choices: ["their", "there", "they're", "thier"], answer: 2 },
      { text: "Homophone: I left my book over ___ .", choices: ["their", "there", "they're", "thier"], answer: 1 },
      { text: "Homophone: ___ shoes are muddy.", choices: ["their", "there", "they're", "thier"], answer: 0 },
      { text: "Homophone: I want ___ go home.", choices: ["to", "two", "too", "twoo"], answer: 0 },
      { text: "Homophone: He has ___ apples.", choices: ["to", "two", "too", "twoo"], answer: 1 },
      { text: "Homophone: It is ___ cold.", choices: ["to", "two", "too", "twoo"], answer: 2 },
      { text: "Homophone: ___ raining outside.", choices: ["its", "it's", "its'", "itss"], answer: 1 },
      { text: "Homophone: The dog wagged ___ tail.", choices: ["its", "it's", "its'", "itss"], answer: 0 },
      { text: "Choose the right word: 'I want to know ___ name.'", choices: ["your", "you're", "yore", "yur"], answer: 0 },
      { text: "Choose: '___ going to be late.'", choices: ["Your", "You're", "Yore", "Yur"], answer: 1 },
      { text: "Choose: 'I ___ the truth.'", choices: ["know", "no", "now", "knoe"], answer: 0 },
      { text: "Choose: '___ way am I doing that.'", choices: ["Know", "No", "Now", "Knoe"], answer: 1 },
      { text: "Choose: 'I ate the ___ meal.'", choices: ["hole", "whole", "hoel", "wole"], answer: 1 },
      { text: "Choose: 'I dug a ___.'", choices: ["hole", "whole", "hoel", "wole"], answer: 0 },
      { text: "Choose: '___ going to the store?'", choices: ["Whose", "Who's", "Whoose", "Whos"], answer: 1 },
      { text: "Choose: '___ book is this?'", choices: ["Whose", "Who's", "Whoose", "Whos"], answer: 0 },
      { text: "Choose: 'I want to ___ the rule.' (agree)", choices: ["accept", "except", "expect", "exept"], answer: 0 },
      { text: "Choose: 'Everyone came ___ Tom.' (apart from)", choices: ["accept", "except", "expect", "exept"], answer: 1 },
      // Plurals
      { text: "Which is the plural of 'leaf'?", choices: ["leafs", "leaves", "leafes", "leavies"], answer: 1 },
      { text: "Which is the plural of 'child'?", choices: ["childs", "childes", "children", "childies"], answer: 2 },
      { text: "Which is the plural of 'foot'?", choices: ["foots", "feets", "feet", "footes"], answer: 2 },
      { text: "Which is the plural of 'wolf'?", choices: ["wolfs", "wolves", "wolfes", "wolvs"], answer: 1 },
      { text: "Which is the plural of 'goose'?", choices: ["gooses", "geese", "gooses'", "gees"], answer: 1 },
      // Suffix rules
      { text: "Add the suffix -ed: 'hop' becomes...", choices: ["hoped", "hopd", "hopped", "hoping"], answer: 2 },
      { text: "Add the suffix -ing: 'run' becomes...", choices: ["runing", "runned", "running", "ranning"], answer: 2 },
      { text: "Add the suffix -ed: 'play' becomes...", choices: ["played", "plaied", "playd", "plaed"], answer: 0 },
      // Silent letters
      { text: "Which is correct?", choices: ["nee", "knee", "knea", "neew"], answer: 1 },
      { text: "Which is correct?", choices: ["rite", "wrute", "write", "wraite"], answer: 2 },
      { text: "Which is correct?", choices: ["lam", "lamb", "laum", "lambb"], answer: 1 },
      { text: "Which is correct?", choices: ["nife", "knife", "knyfe", "knive"], answer: 1 },
      { text: "Which is correct?", choices: ["thum", "thumb", "thume", "thumm"], answer: 1 },
      { text: "Which is correct?", choices: ["sord", "sword", "swerd", "sworde"], answer: 1 },
      // ie vs ei
      { text: "Which is correct? (a slice of pie)", choices: ["peice", "piece", "peace", "piecce"], answer: 1 },
      { text: "Which is correct? (top of a room)", choices: ["cieling", "ceiling", "sieling", "celing"], answer: 1 },
      { text: "Which is correct? (how heavy)", choices: ["wieght", "weight", "waight", "weite"], answer: 1 },
      { text: "Which is correct? (head of a tribe)", choices: ["chief", "cheif", "cheef", "cheaf"], answer: 0 },
      // -tion / -sion
      { text: "Which is correct?", choices: ["nashun", "nation", "nashon", "nattion"], answer: 1 },
      { text: "Which is correct?", choices: ["action", "akshun", "axion", "acshun"], answer: 0 },
      { text: "Which is correct?", choices: ["posision", "position", "positon", "possition"], answer: 1 },
      { text: "Which is correct?", choices: ["divishun", "division", "divizion", "divission"], answer: 1 },
      // Greek/Latin roots (meaning)
      { text: "What does 'trans-' mean?", choices: ["under", "across", "before", "around"], answer: 1 },
      { text: "What does 'auto-' mean?", choices: ["self", "other", "many", "few"], answer: 0 },
      { text: "What does 'bio-' mean?", choices: ["life", "death", "color", "shape"], answer: 0 },
      { text: "What does 'photo-' mean?", choices: ["sound", "light", "water", "rock"], answer: 1 },
    ],
    grammar: [
      // Parts of speech identification
      { text: "Which is a proper noun?", choices: ["city", "Houston", "park", "river"], answer: 1 },
      { text: "Which is a common noun?", choices: ["Sarah", "Texas", "school", "Monday"], answer: 2 },
      { text: "Which is an adjective?", choices: ["jump", "happy", "carefully", "and"], answer: 1 },
      { text: "Which is an adverb?", choices: ["fast", "quickly", "house", "blue"], answer: 1 },
      { text: "Which is a pronoun?", choices: ["dog", "she", "running", "tall"], answer: 1 },
      { text: "Which is a conjunction?", choices: ["and", "happy", "red", "jumps"], answer: 0 },
      { text: "Which is a noun?", choices: ["run", "beautiful", "school", "slowly"], answer: 2 },
      { text: "Which is an adjective?", choices: ["book", "beautiful", "run", "sing"], answer: 1 },
      { text: "Which is a verb?", choices: ["jump", "table", "blue", "soft"], answer: 0 },
      { text: "Which is a preposition?", choices: ["on", "big", "run", "happy"], answer: 0 },
      { text: "Which is a preposition?", choices: ["under", "run", "blue", "soft"], answer: 0 },
      { text: "Which is a conjunction?", choices: ["but", "ran", "big", "hat"], answer: 0 },
      { text: "Which is a pronoun?", choices: ["they", "walk", "big", "smart"], answer: 0 },
      // In context
      { text: "In 'The big red dog,' what are 'big' and 'red'?", choices: ["nouns", "verbs", "adjectives", "adverbs"], answer: 2 },
      { text: "In 'She runs quickly,' what is 'quickly'?", choices: ["noun", "verb", "adjective", "adverb"], answer: 3 },
      // Subject and predicate
      { text: "Identify the subject in: 'The cat slept on the rug.'", choices: ["the cat", "slept", "rug", "on"], answer: 0 },
      { text: "Identify the predicate in: 'My brother plays soccer.'", choices: ["My brother", "plays soccer", "soccer", "my"], answer: 1 },
      { text: "In 'The fluffy dog barked loudly,' what's the subject?", choices: ["The fluffy dog", "barked", "loudly", "the"], answer: 0 },
      { text: "In 'My sister sings beautifully,' what's the predicate?", choices: ["My sister", "sings beautifully", "beautifully", "my"], answer: 1 },
      { text: "In 'Tom ate pizza,' the subject is...?", choices: ["Tom", "ate", "pizza", "ate pizza"], answer: 0 },
      { text: "In 'They ran to the park,' the predicate is...?", choices: ["They", "ran to the park", "the park", "ran"], answer: 1 },
      // Verb tenses
      { text: "Which is past tense of 'go'?", choices: ["goed", "gone", "went", "going"], answer: 2 },
      { text: "Which is past tense of 'eat'?", choices: ["eated", "ate", "eaten", "eating"], answer: 1 },
      { text: "Which is past tense of 'see'?", choices: ["seen", "saw", "seed", "seeing"], answer: 1 },
      { text: "Which is past tense of 'run'?", choices: ["runned", "running", "ran", "run"], answer: 2 },
      { text: "Past tense of 'sing'?", choices: ["singed", "sing", "sang", "sung"], answer: 2 },
      { text: "Past tense of 'write'?", choices: ["writed", "wrote", "writ", "writing"], answer: 1 },
      { text: "Past tense of 'speak'?", choices: ["speaked", "spoke", "spoken", "spake"], answer: 1 },
      { text: "Past tense of 'bring'?", choices: ["bringed", "brung", "brought", "bringing"], answer: 2 },
      { text: "Past tense of 'catch'?", choices: ["catched", "caught", "cought", "catching"], answer: 1 },
      { text: "Past tense of 'fly'?", choices: ["flied", "flew", "flown", "flying"], answer: 1 },
      { text: "Past tense of 'swim'?", choices: ["swimmed", "swam", "swum", "swims"], answer: 1 },
      { text: "Past tense of 'take'?", choices: ["taked", "took", "taken", "taking"], answer: 1 },
      { text: "Future tense: 'I ___ run tomorrow.'", choices: ["will", "did", "have", "am"], answer: 0 },
      // Comparative / superlative
      { text: "Comparative of 'big' is...?", choices: ["big", "bigger", "biggest", "more big"], answer: 1 },
      { text: "Superlative of 'small' is...?", choices: ["small", "smaller", "smallest", "more small"], answer: 2 },
      { text: "Comparative of 'good' is...?", choices: ["gooder", "better", "best", "more good"], answer: 1 },
      { text: "Superlative of 'good' is...?", choices: ["gooder", "better", "best", "most good"], answer: 2 },
      { text: "Comparative of 'bad' is...?", choices: ["badder", "worse", "worst", "more bad"], answer: 1 },
      { text: "Superlative of 'bad' is...?", choices: ["worse", "worst", "baddest", "most bad"], answer: 1 },
      // Linking vs action
      { text: "'Is' in 'She is happy' is a...?", choices: ["action verb", "linking verb", "noun", "adjective"], answer: 1 },
      { text: "'Jumped' in 'He jumped high' is a...?", choices: ["linking verb", "action verb", "noun", "adverb"], answer: 1 },
      { text: "'Seems' in 'It seems easy' is a...?", choices: ["action verb", "linking verb", "preposition", "noun"], answer: 1 },
      // Sentence correctness
      { text: "Which sentence is correct?", choices: ["She don't like fish.", "She doesn't like fish.", "She not like fish.", "She no like fish."], answer: 1 },
      { text: "Which sentence is correct?", choices: ["Me and Sam went.", "Sam and I went.", "I and Sam went.", "Sam and me went."], answer: 1 },
      // Commas
      { text: "Where do commas go? 'I bought milk eggs and bread.'", choices: ["milk eggs and bread", "milk, eggs, and bread", "milk eggs, and bread", "milk eggs and, bread"], answer: 1 },
      { text: "Where should the comma go? 'Yes I will help.'", choices: ["Yes I, will help.", "Yes, I will help.", "Yes I will, help.", "Yes I will help,"], answer: 1 },
      // Quotation marks
      { text: "Which uses quotation marks correctly?", choices: ["She said hello.", "She said, \"hello\".", "She said, \"Hello.\"", "She said: hello"], answer: 2 },
      { text: "What punctuation goes around someone's exact words?", choices: ["parentheses", "quotation marks", "brackets", "asterisks"], answer: 1 },
      // Apostrophes
      { text: "Apostrophes show...?", choices: ["only questions", "possession or contractions", "only the ending", "only past tense"], answer: 1 },
      { text: "Which is correct? 'The ___ tail wagged.'", choices: ["dogs", "dog's", "dogs'", "dogses"], answer: 1 },
      { text: "Which is correct? 'The ___ tails wagged.' (many dogs)", choices: ["dog's", "dogs", "dogs'", "dogses"], answer: 2 },
      // Contractions
      { text: "Contraction for 'do not'?", choices: ["donot", "don't", "do'nt", "dont"], answer: 1 },
      { text: "Contraction for 'I am'?", choices: ["Im", "I'm", "Iam", "I'am"], answer: 1 },
      { text: "Contraction for 'they are'?", choices: ["thery", "there", "they're", "theyre"], answer: 2 },
      { text: "Contraction for 'we will'?", choices: ["well", "we'll", "wewill", "we'l"], answer: 1 },
      { text: "Contraction for 'is not'?", choices: ["isnt", "isn't", "is'nt", "isnot"], answer: 1 },
      // Sentence types
      { text: "Which type of sentence is 'Watch out!'?", choices: ["statement", "question", "exclamation", "command"], answer: 2 },
      { text: "Which type of sentence is 'Close the door.'?", choices: ["statement", "question", "exclamation", "command"], answer: 3 },
      { text: "Which type of sentence is 'I love pizza.'?", choices: ["statement", "question", "exclamation", "command"], answer: 0 },
      { text: "Which type of sentence is 'Where are you?'?", choices: ["statement", "question", "exclamation", "command"], answer: 1 },
      // Pronouns
      { text: "'I ate ___ lunch.'", choices: ["my", "mine", "I", "me"], answer: 0 },
      { text: "'That book is ___.'", choices: ["my", "mine", "I", "me"], answer: 1 },
      // Possessives
      { text: "The dog's bowl. Is 'dog's' singular or plural possessive?", choices: ["singular", "plural", "neither", "both"], answer: 0 },
      { text: "The dogs' bowls. Is 'dogs'' singular or plural possessive?", choices: ["singular", "plural", "neither", "both"], answer: 1 },
      { text: "What's the possessive form of 'the cat'?", choices: ["the cats", "the cat's", "the cats'", "the catses"], answer: 1 },
      { text: "What's the possessive form of 'the children'?", choices: ["the childrens", "the children's", "the childrens'", "the child's"], answer: 1 },
      // Helping verbs
      { text: "In 'I am running,' the helping verb is...?", choices: ["I", "am", "running", "ing"], answer: 1 },
      { text: "In 'She has eaten,' the helping verb is...?", choices: ["She", "has", "eaten", "eat"], answer: 1 },
      { text: "In 'They will play,' the helping verb is...?", choices: ["They", "will", "play", "ing"], answer: 1 },
      { text: "Which is a helping verb?", choices: ["am", "dog", "run", "fast"], answer: 0 },
      // Fragments vs run-ons
      { text: "A complete sentence has a subject and a...?", choices: ["title", "predicate (verb)", "comma", "name"], answer: 1 },
      { text: "'Ran fast.' is a...?", choices: ["complete sentence", "fragment", "run-on", "question"], answer: 1 },
      { text: "'I ran I fell.' is a...?", choices: ["complete sentence", "fragment", "run-on", "question"], answer: 2 },
      { text: "'I ran and fell.' is a...?", choices: ["complete sentence", "fragment", "run-on", "question"], answer: 0 },
      // 'who' vs 'which'
      { text: "We use 'who' for people. We use ___ for things.", choices: ["which", "where", "why", "with"], answer: 0 },
    ],
  },
};

// Helper: get a random question from a grade + subject
function getRandomQuestion(grade, subject) {
  const pool = QUESTIONS[grade] && QUESTIONS[grade][subject];
  if (!pool || pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

// Helper: shuffle answer choices but track correct index
function shuffleQuestion(q) {
  const indexed = q.choices.map((c, i) => ({ c, correct: i === q.answer }));
  for (let i = indexed.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [indexed[i], indexed[j]] = [indexed[j], indexed[i]];
  }
  return {
    text: q.text,
    choices: indexed.map(x => x.c),
    answer: indexed.findIndex(x => x.correct),
  };
}
